-- MySQL Script generated by MySQL Workbench
-- 10/11/14 07:58:54
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema henrrique
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `henrrique` DEFAULT CHARACTER SET latin1 ;
USE `henrrique` ;

-- -----------------------------------------------------
-- Table `henrrique`.`anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`anexo` (
  `idanexo` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `caminho_servidor` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idanexo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`pais` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NULL DEFAULT NULL,
  `sigla` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `henrrique`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`estado` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(75) NULL DEFAULT NULL,
  `uf` VARCHAR(5) NULL DEFAULT NULL,
  `pais_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_estado_pais_idx` (`pais_id` ASC),
  CONSTRAINT `fk_estado_pais`
    FOREIGN KEY (`pais_id`)
    REFERENCES `henrrique`.`pais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `henrrique`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`cidade` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NULL DEFAULT NULL,
  `estado_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidade_estado1_idx` (`estado_id` ASC),
  CONSTRAINT `fk_cidade_estado1`
    FOREIGN KEY (`estado_id`)
    REFERENCES `henrrique`.`estado` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2027
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `henrrique`.`natureza_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`natureza_consulta` (
  `idnatureza_consulta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `natureza` VARCHAR(255) NOT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`idnatureza_consulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`prioridade_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`prioridade_consulta` (
  `idprioridade_consulta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `dias` INT(11) NULL DEFAULT NULL,
  `horas` INT(11) NULL DEFAULT NULL,
  `minutos` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idprioridade_consulta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`usuarios` (
  `iduser` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `apelido` VARCHAR(255) NULL,
  `email` VARCHAR(255) NOT NULL,
  `level` INT(11) NULL DEFAULT '0',
  `ultimo_update` DATETIME NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `ultima_conexao` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `status` ENUM('0','1') NOT NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`consulta` (
  `idconsulta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `usuarios_iduser` INT(10) UNSIGNED NOT NULL,
  `natureza_consulta_idnatureza_consulta` INT(10) UNSIGNED NOT NULL,
  `assunto` VARCHAR(100) NOT NULL,
  `descricao` TEXT NOT NULL,
  `prioridade_consulta_idprioridade_consulta` INT(10) UNSIGNED NULL,
  `colaborador_consulta` INT(10) UNSIGNED NULL,
  `data_consulta` DATETIME NOT NULL,
  `entrega_consulta` DATETIME NULL,
  `etapa` ENUM(  '0',  '1',  '2',  '3',  '4',  '5' ) NOT NULL DEFAULT '1' COMMENT 'Onde 0 e quando o usuario precisa rever, 1 chegou ao coordenador, 2 o colaborar precisa rever, 3 chegou ao colaborador, 4 fase de aprovacao do coordenador para a resposta do advogado, 5 finalizado',
  PRIMARY KEY (`idconsulta`),
  INDEX `fk_consulta_usuarios1_idx` (`usuarios_iduser` ASC),
  INDEX `fk_consulta_natureza_consulta1_idx` (`natureza_consulta_idnatureza_consulta` ASC),
  INDEX `fk_consulta_prioridade_consulta1_idx` (`prioridade_consulta_idprioridade_consulta` ASC),
  INDEX `fk_consulta_usuarios2_idx` (`colaborador_consulta` ASC),
  CONSTRAINT `fk_consulta_natureza_consulta1`
    FOREIGN KEY (`natureza_consulta_idnatureza_consulta`)
    REFERENCES `henrrique`.`natureza_consulta` (`idnatureza_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_prioridade_consulta1`
    FOREIGN KEY (`prioridade_consulta_idprioridade_consulta`)
    REFERENCES `henrrique`.`prioridade_consulta` (`idprioridade_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_usuarios1`
    FOREIGN KEY (`usuarios_iduser`)
    REFERENCES `henrrique`.`usuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_usuarios2`
    FOREIGN KEY (`colaborador_consulta`)
    REFERENCES `henrrique`.`usuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`consulta_has_anexo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`consulta_has_anexo` (
  `consulta_idconsulta` INT(10) UNSIGNED NOT NULL,
  `anexo_idanexo` INT(10) UNSIGNED NOT NULL,
  `data_anexo` DATETIME NOT NULL,
  `status` ENUM('0','1') NOT NULL DEFAULT '1',
  PRIMARY KEY (`consulta_idconsulta`, `anexo_idanexo`),
  INDEX `fk_consulta_has_anexo_anexo1_idx` (`anexo_idanexo` ASC),
  INDEX `fk_consulta_has_anexo_consulta1_idx` (`consulta_idconsulta` ASC),
  CONSTRAINT `fk_consulta_has_anexo_anexo1`
    FOREIGN KEY (`anexo_idanexo`)
    REFERENCES `henrrique`.`anexo` (`idanexo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_has_anexo_consulta1`
    FOREIGN KEY (`consulta_idconsulta`)
    REFERENCES `henrrique`.`consulta` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`tipo_pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`tipo_pessoa` (
  `idtipo_pessoa` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `dashboard` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`idtipo_pessoa`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`pessoas` (
  `idpessoa` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(80) NOT NULL,
  `sobrenome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(15) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NULL DEFAULT NULL,
  `rg` VARCHAR(10) NULL DEFAULT NULL,
  `cpf` VARCHAR(15) NULL DEFAULT NULL,
  `cnpj` VARCHAR(20) NULL DEFAULT NULL,
  `data_nasc` DATE NULL DEFAULT NULL,
  `ultimo_update` DATETIME NULL DEFAULT NULL,
  `status` ENUM('0','1') NOT NULL,
  `usuarios_iduser` INT(10) UNSIGNED NULL,
  `tipo_pessoa_idtipo_pessoa` INT(10) UNSIGNED NULL,
  `pessoas_idpessoa` INT(10) UNSIGNED NULL,
  PRIMARY KEY (`idpessoa`),
  UNIQUE INDEX `usuarios_iduser_UNIQUE` (`usuarios_iduser` ASC),
  INDEX `fk_pessoas_usuarios1_idx` (`usuarios_iduser` ASC),
  INDEX `fk_pessoas_tipo_pessoa1_idx` (`tipo_pessoa_idtipo_pessoa` ASC),
  INDEX `fk_pessoas_pessoas1_idx` (`pessoas_idpessoa` ASC),
  CONSTRAINT `fk_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_idpessoa`)
    REFERENCES `henrrique`.`pessoas` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_tipo_pessoa1`
    FOREIGN KEY (`tipo_pessoa_idtipo_pessoa`)
    REFERENCES `henrrique`.`tipo_pessoa` (`idtipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_usuarios1`
    FOREIGN KEY (`usuarios_iduser`)
    REFERENCES `henrrique`.`usuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`consulta_has_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`consulta_has_pessoas` (
  `consulta_idconsulta` INT(10) UNSIGNED NOT NULL,
  `pessoas_idpessoa` INT(10) UNSIGNED NOT NULL,
  `data_selecionado` DATETIME NOT NULL,
  PRIMARY KEY (`consulta_idconsulta`, `pessoas_idpessoa`),
  INDEX `fk_consulta_has_pessoas_pessoas1_idx` (`pessoas_idpessoa` ASC),
  INDEX `fk_consulta_has_pessoas_consulta1_idx` (`consulta_idconsulta` ASC),
  CONSTRAINT `fk_consulta_has_pessoas_consulta1`
    FOREIGN KEY (`consulta_idconsulta`)
    REFERENCES `henrrique`.`consulta` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_consulta_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoas_idpessoa`)
    REFERENCES `henrrique`.`pessoas` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`endereco` (
  `idendereco` INT(11) UNSIGNED NOT NULL,
  `logradouro` VARCHAR(255) NOT NULL,
  `numero` VARCHAR(255) NOT NULL,
  `complemento` VARCHAR(255) NULL DEFAULT NULL,
  `bairro` VARCHAR(255) NOT NULL,
  `cep` VARCHAR(10) NULL DEFAULT NULL,
  `pessoas_idpessoa` INT(10) UNSIGNED NOT NULL,
  `cidade_id` INT(11) UNSIGNED NOT NULL,
  PRIMARY KEY (`idendereco`),
  INDEX `fk_endereco_pessoas1_idx` (`pessoas_idpessoa` ASC),
  INDEX `fk_endereco_cidade1_idx` (`cidade_id` ASC),
  CONSTRAINT `fk_endereco_cidade1`
    FOREIGN KEY (`cidade_id`)
    REFERENCES `henrrique`.`cidade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_endereco_pessoas1`
    FOREIGN KEY (`pessoas_idpessoa`)
    REFERENCES `henrrique`.`pessoas` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`permicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`permicoes` (
  `pessoas_idpessoa` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`pessoas_idpessoa`),
  INDEX `fk_permicoes_pessoas1_idx` (`pessoas_idpessoa` ASC),
  CONSTRAINT `fk_permicoes_pessoas1`
    FOREIGN KEY (`pessoas_idpessoa`)
    REFERENCES `henrrique`.`pessoas` (`idpessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`pre_permicoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`pre_permicoes` (
  `tipo_pessoa_idtipo_pessoa` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`tipo_pessoa_idtipo_pessoa`),
  INDEX `fk_pre_permicoes_tipo_pessoa1_idx` (`tipo_pessoa_idtipo_pessoa` ASC),
  CONSTRAINT `fk_pre_permicoes_tipo_pessoa1`
    FOREIGN KEY (`tipo_pessoa_idtipo_pessoa`)
    REFERENCES `henrrique`.`tipo_pessoa` (`idtipo_pessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`resposta_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`resposta_consulta` (
  `idresposta_consulta` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `acao` TEXT NOT NULL,
  `fundamento` TEXT NOT NULL,
  `data_resposta` DATETIME NOT NULL,
  `usuarios_iduser` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`idresposta_consulta`),
  INDEX `fk_resposta_consulta_usuarios1_idx` (`usuarios_iduser` ASC),
  CONSTRAINT `fk_resposta_consulta_usuarios1`
    FOREIGN KEY (`usuarios_iduser`)
    REFERENCES `henrrique`.`usuarios` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `henrrique`.`resposta_consulta_has_consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `henrrique`.`resposta_consulta_has_consulta` (
  `resposta_consulta_idresposta_consulta` INT(10) UNSIGNED NOT NULL,
  `consulta_idconsulta` INT(10) UNSIGNED NOT NULL,
  PRIMARY KEY (`resposta_consulta_idresposta_consulta`, `consulta_idconsulta`),
  INDEX `fk_resposta_consulta_has_consulta_consulta1_idx` (`consulta_idconsulta` ASC),
  INDEX `fk_resposta_consulta_has_consulta_resposta_consulta1_idx` (`resposta_consulta_idresposta_consulta` ASC),
  CONSTRAINT `fk_resposta_consulta_has_consulta_consulta1`
    FOREIGN KEY (`consulta_idconsulta`)
    REFERENCES `henrrique`.`consulta` (`idconsulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resposta_consulta_has_consulta_resposta_consulta1`
    FOREIGN KEY (`resposta_consulta_idresposta_consulta`)
    REFERENCES `henrrique`.`resposta_consulta` (`idresposta_consulta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
